### ISSUE TITLE
0.11.0 not indexing

### ISSUE THREAD

**Issue by dgoradia-atlas** [PierreRambaud/gemirro#13]
Version 0.11.0 is not indexing. `public/quick/Marshal.4.8/` is empty after `gemirro index`. Further `gemirro  server --start` does not listen on port 2000. A telnet to that port does not connect.

**Comment by PierreRambaud** [comment]
Hi,

Can you tell me more, I can't reproduce.

**Comment by dgoradia-atlas** [comment]
I was doing almost the same thing except I was checking out tags/0.11.0 instead of master and my Marshal.4.8 directory is empty even after a `gemirro index`. 

I'll try again against the master branch and report back.

**Comment by dgoradia-atlas** [comment]
So here are my results from the master branch.

```
# git checkout master
Previous HEAD position was b151aa5... Bump to 0.10.5
Switched to branch 'master'
Your branch is behind 'origin/master' by 6 commits, and can be fast-forwarded.
# git pull
Warning: Permanently added the RSA host key for IP address '192.30.252.128' to the list of known hosts.
remote: Counting objects: 3, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), done.
From github.com:PierreRambaud/gemirro
   5c159ec..25b9c21  master     -> origin/master
Updating 2afcf06..25b9c21
Fast-forward
 .gitignore                            |   11 +++--
 MANIFEST                              |    2 +
 gemirro.gemspec                       |    7 ++-
 lib/gemirro/configuration.rb          |   36 +++++++++++++--
 lib/gemirro/gem.rb                    |   31 +++++++++++--
 lib/gemirro/gems_fetcher.rb           |   81 ++++++++++++++++++++++++++-------
 lib/gemirro/server.rb                 |   20 +++++---
 lib/gemirro/source.rb                 |   21 +++++++++
 lib/gemirro/version.rb                |    2 +-
 lib/gemirro/versions_fetcher.rb       |    2 +-
 lib/gemirro/versions_file.rb          |   17 +++++--
 spec/gemirro/configuration_spec.rb    |    4 +-
 spec/gemirro/gems_fetcher_spec.rb     |   65 ++++++++++++++++++++++-----
 spec/gemirro/source_spec.rb           |    8 +++
 spec/gemirro/versions_fetcher_spec.rb |    3 +-
 spec/gemirro/versions_file_spec.rb    |   21 +++++++--
 16 files changed, 264 insertions(+), 67 deletions(-)
```
```
# gem list gemirro

*** LOCAL GEMS ***

# bundle exec rake install
gemirro 0.11.0 built to pkg/gemirro-0.11.0.gem.
gemirro (0.11.0) installed.
# gem list gemirro

*** LOCAL GEMS ***

gemirro (0.11.0)
```
```
# mkdir -p /srv/http/gemserver
# bundle exec gemirro init /srv/http/gemserver
Initialized empty mirror in /srv/http/gemserver
# vi /srv/http/gemserver/config.rb
```

I backed up close to 1000 gems which I copy back to the public directory:
```
# ll /srv/http/gemserver/public/
dist/ gems/ 
# ll /srv/http/gemserver/public/gems/
total 0
# cp -rf ~/gems/public/gems/* /srv/http/gemserver/public/gems/
# tree /srv/http/gemserver/public/gems/ | tail -n -1
0 directories, 960 files
```
```
# bundle exec gemirro update -c /srv/http/gemserver/config.rb 
I, [2015-08-01T13:57:58.018272 #27961]  INFO -- : Updating rubygems (http://rubygems.org)
I, [2015-08-01T13:58:03.899691 #27961]  INFO -- : Fetching rake-0.9.0.beta.0.gem
I, [2015-08-01T13:58:04.309174 #27961]  INFO -- : Fetching rake-0.9.0.beta.1.gem
I, [2015-08-01T13:58:04.570157 #27961]  INFO -- : Fetching rake-0.9.0.beta.2.gem
I, [2015-08-01T13:58:04.766182 #27961]  INFO -- : Fetching rake-0.9.0.beta.4.gem
...
# tree /srv/http/gemserver/public/gems/ | tail -n -1
0 directories, 1004 files
# ll /srv/http/gemserver/public/
total 44
drwxr-xr-x. 5 root root  4096 Aug  1 13:55 dist
drwxr-xr-x. 2 root root 40960 Aug  1 13:59 gems
```
```
# bundle exec gemirro index -c /srv/http/gemserver/config.rb 
I, [2015-08-01T14:01:10.084860 #5058]  INFO -- : Generating indexes
I, [2015-08-01T14:01:10.087205 #5058]  INFO -- : [1/1003]: Processing builder-2.1.2.gem
I, [2015-08-01T14:01:10.087346 #5058]  INFO -- : [2/1003]: Processing rack-1.6.4.gem
I, [2015-08-01T14:01:10.087426 #5058]  INFO -- : [3/1003]: Processing safe_yaml-1.0.2.gem
I, [2015-08-01T14:01:10.087505 #5058]  INFO -- : [4/1003]: Processing chef-0.9.4.gem
I, [2015-08-01T14:01:10.087585 #5058]  INFO -- : [5/1003]: Processing mixlib-shellout-2.0.0.gem
I, [2015-08-01T14:01:10.087653 #5058]  INFO -- : [6/1003]: Processing rspec-core-2.2.0.gem
I, [2015-08-01T14:01:10.087722 #5058]  INFO -- : [7/1003]: Processing specinfra-2.25.0.gem
I, [2015-08-01T14:01:10.090847 #5058]  INFO -- : [8/1003]: Processing pry-0.9.9.5.gem
...
I, [2015-08-01T14:01:10.260440 #5058]  INFO -- : [1003/1003]: Processing net-scp-1.1.2.gem
I, [2015-08-01T14:01:10.262218 #5058]  INFO -- : Download from source: specs.4.8
I, [2015-08-01T14:01:10.400503 #5058]  INFO -- : Download from source: specs.4.8.gz
I, [2015-08-01T14:01:23.577981 #5058]  INFO -- : Download from source: latest_specs.4.8
I, [2015-08-01T14:01:23.631542 #5058]  INFO -- : Download from source: latest_specs.4.8.gz
I, [2015-08-01T14:01:27.880805 #5058]  INFO -- : Download from source: prerelease_specs.4.8
I, [2015-08-01T14:01:27.945392 #5058]  INFO -- : Download from source: prerelease_specs.4.8.gz
```
```
# ll /srv/http/gemserver/public/
total 3524
drwxr-xr-x. 5 root root    4096 Aug  1 13:55 dist
drwxr-xr-x. 2 root root   40960 Aug  1 13:59 gems
-rw-r--r--. 1 root root      53 Aug  1 14:01 latest_specs.4.8
-rw-------. 1 root root  886851 Aug  1 14:01 latest_specs.4.8.gz
-rw-------. 1 root root      24 Aug  1 14:01 latest_specs.4.8.gz.orig
-rw-r--r--. 1 root root       4 Aug  1 14:01 prerelease_specs.4.8
-rw-------. 1 root root  157319 Aug  1 14:01 prerelease_specs.4.8.gz
-rw-------. 1 root root      24 Aug  1 14:01 prerelease_specs.4.8.gz.orig
drwxr-xr-x. 3 root root    4096 Aug  1 14:01 quick
-rw-r--r--. 1 root root      53 Aug  1 14:01 specs.4.8
-rw-------. 1 root root 2482563 Aug  1 14:01 specs.4.8.gz
-rw-------. 1 root root      24 Aug  1 14:01 specs.4.8.gz.orig
```
```
# ll /srv/http/gemserver/public/quick/Marshal.4.8/
total 0
```

And here is my config.rb file
```
# cat /srv/http/gemserver/config.rb 
# -*- coding: utf-8 -*-
# This is the main configuration file for your RubyGems mirror. Here you can
# change settings such as the location to store Gem files in and what source
# and Gems you'd like to mirror at start.
Gemirro.configuration.configure do
  # Define sinatra environment
  environment :production

  # The directory to store indexing information as well as the Gem files in.
  destination File.expand_path('../public', __FILE__)

  # If you're in development mode your probably want to switch to a debug
  # logging level.
  logger.level = Logger::INFO

  # If you want to run your server on a specific host and port, you must
  # change the following parameters (server_host and server_port).
  #
  server.host 'gemserver.mydomain.io'
  server.port '2000'
  server.access_log File.expand_path('../logs/access.log', __FILE__)
  server.error_log File.expand_path('../logs/error.log', __FILE__)

  # You must define a source wich where gems will be downloaded.
  # All gem in the block will be downloaded with the update command.
  # Other gems will be downloaded with the server.
  define_source 'rubygems', 'http://rubygems.org' do
    gem 'rack', '>= 1.0.0'
    gem 'rake'
    gem 'chef', '>= 12.0.0'
    gem 'chef-vault', '>= 2.5.0'
    gem 'berkshelf', '>= 3.2.3'
    gem 'chef-vault', '>= 2.5.0'
    gem 'chef-vault-testfixtures', '>= 0.5.0'
    gem 'chefspec', '>= 4.2.0'
    gem 'foodcritic', '>= 4.0.0'
    gem 'test-kitchen', '>= 0.18.0'
    gem 'nokogiri'
    gem 'net-ping'
  end
end
```

**Comment by dgoradia-atlas** [comment]
Switched the config to debug, here's the output.
```
# bundle exec gemirro index -c /srv/http/gemserver/config.rb 
I, [2015-08-01T15:07:33.216440 #17468]  INFO -- : Generating indexes
I, [2015-08-01T15:07:33.226053 #17468]  INFO -- : [1/1003]: Processing builder-2.1.2.gem
D, [2015-08-01T15:07:33.226208 #17468] DEBUG -- : Unable to process /srv/http/gemserver/public/gems/builder-2.1.2.gem
undefined method `new' for Gem::Package:Module (NoMethodError)
	/opt/gemirro/lib/gemirro/indexer.rb:169:in `block in map_gems_to_specs'
	/opt/gemirro/lib/gemirro/indexer.rb:158:in `map'
	/opt/gemirro/lib/gemirro/indexer.rb:158:in `with_index'
	/opt/gemirro/lib/gemirro/indexer.rb:158:in `map_gems_to_specs'
	/opt/gemirro/lib/gemirro/indexer.rb:140:in `build_indicies'
	/opt/opscode/embedded/lib/ruby/site_ruby/2.1.0/rubygems/indexer.rb:456:in `generate_index'
	/opt/gemirro/lib/gemirro/cli/index.rb:23:in `block (2 levels) in <top (required)>'
	/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/slop-3.6.0/lib/slop.rb:260:in `call'
	/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
	/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
	/opt/gemirro/bin/gemirro:7:in `<top (required)>'
	/opt/opscode/embedded/lib/ruby/gems/2.1.0/bin/gemirro:23:in `load'
	/opt/opscode/embedded/lib/ruby/gems/2.1.0/bin/gemirro:23:in `<main>'
I, [2015-08-01T15:07:33.226258 #17468]  INFO -- : [2/1003]: Processing rack-1.6.4.gem
D, [2015-08-01T15:07:33.226320 #17468] DEBUG -- : Unable to process /srv/http/gemserver/public/gems/rack-1.6.4.gem
undefined method `new' for Gem::Package:Module (NoMethodError)
	/opt/gemirro/lib/gemirro/indexer.rb:169:in `block in map_gems_to_specs'
	/opt/gemirro/lib/gemirro/indexer.rb:158:in `map'
	/opt/gemirro/lib/gemirro/indexer.rb:158:in `with_index'
	/opt/gemirro/lib/gemirro/indexer.rb:158:in `map_gems_to_specs'
	/opt/gemirro/lib/gemirro/indexer.rb:140:in `build_indicies'
	/opt/opscode/embedded/lib/ruby/site_ruby/2.1.0/rubygems/indexer.rb:456:in `generate_index'
	/opt/gemirro/lib/gemirro/cli/index.rb:23:in `block (2 levels) in <top (required)>'
	/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/slop-3.6.0/lib/slop.rb:260:in `call'
	/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
	/opt/opscode/embedded/lib/ruby/gems/2.1.0/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
	/opt/gemirro/bin/gemirro:7:in `<top (required)>'
	/opt/opscode/embedded/lib/ruby/gems/2.1.0/bin/gemirro:23:in `load'
	/opt/opscode/embedded/lib/ruby/gems/2.1.0/bin/gemirro:23:in `<main>'
```

**Comment by dgoradia-atlas** [comment]
Ok so I think I've got it, I should've set the logging level to debug before. 

```
# gem -v
1.8.24
```

My gem version was too old.

```
gem update --system
```

Fixed the indexing issue. 
```
# tree public/quick/Marshal.4.8/ | tail -n -1
0 directories, 1003 files
```

**Comment by PierreRambaud** [comment]
Thanks a lot for the feedback. I must find a way to force gem version to be updated on the system.

Regards

**Comment by PierreRambaud** [comment]
I add a line in the README. Don't find anyway to force the update of Rubygems :/

**Comment by PierreRambaud** [comment]
Can't do any more than adding line in README file.
