### ISSUE TITLE
Indexing fails

### ISSUE THREAD

**Issue by hemmrich** [PierreRambaud/gemirro#39]
When trying to index all gems available on rubygems.org, running ```gemirro index``` fails when the function ```build_zlib_file``` is called for file ```prerelease_specs.4.8.gz```.

Stack trace:
```
I, [2016-09-28T03:07:19.300754 #21295]  INFO -- : [729877/729878]: Processing wkhtmltox-binaries-0.13.0.pre.alpha.gem
I, [2016-09-28T03:08:04.170222 #21295]  INFO -- : [729878/729878]: Processing wkhtmltox-binaries-0.13.0.pre.alpha.0.1.gem
D, [2016-09-28T03:15:29.977825 #21295] DEBUG -- : Downloading index into production dir /home/var/gemirro/public
I, [2016-09-28T03:23:16.388504 #21295]  INFO -- : Download from source: specs.4.8
D, [2016-09-28T03:23:16.823280 #21295] DEBUG -- : In build_zlib_file, file: specs.4.8.gz, src: /tmp/gem_generate_index_274264708/specs.4.8.gz, dst: /home/var/gemirro/public/specs.4.8.gz, from: true
I, [2016-09-28T03:23:20.220754 #21295]  INFO -- : Download from source: specs.4.8.gz
I, [2016-09-28T03:23:27.050738 #21295]  INFO -- : Download from source: latest_specs.4.8
D, [2016-09-28T03:23:27.082046 #21295] DEBUG -- : In build_zlib_file, file: latest_specs.4.8.gz, src: /tmp/gem_generate_index_274264708/latest_specs.4.8.gz, dst: /home/var/gemirro/public/latest_specs.4.8.gz, from: true
I, [2016-09-28T03:23:28.146251 #21295]  INFO -- : Download from source: latest_specs.4.8.gz
I, [2016-09-28T03:23:30.259695 #21295]  INFO -- : Download from source: prerelease_specs.4.8
D, [2016-09-28T03:23:30.288585 #21295] DEBUG -- : In build_zlib_file, file: prerelease_specs.4.8.gz, src: /tmp/gem_generate_index_274264708/prerelease_specs.4.8.gz, dst: /home/var/gemirro/public/prerelease_specs.4.8.gz, from: true
/home/lib64/ruby/2.3.0/rubygems/version.rb:207:in `initialize': Malformed version number string one-0.0.1 (ArgumentError)
        from /home/lib64/ruby/2.3.0/rubygems/version.rb:264:in `marshal_load'
        from /home/lib64/ruby/gems/2.3.0/gems/gemirro-0.13.3/lib/gemirro/indexer.rb:307:in `load'
        from /home/lib64/ruby/gems/2.3.0/gems/gemirro-0.13.3/lib/gemirro/indexer.rb:307:in `build_zlib_file'
        from /home/lib64/ruby/gems/2.3.0/gems/gemirro-0.13.3/lib/gemirro/indexer.rb:118:in `block in install_indicies'
        from /home/lib64/ruby/gems/2.3.0/gems/gemirro-0.13.3/lib/gemirro/indexer.rb:110:in `each'
        from /home/lib64/ruby/gems/2.3.0/gems/gemirro-0.13.3/lib/gemirro/indexer.rb:110:in `install_indicies'
        from /home/lib64/ruby/gems/2.3.0/gems/gemirro-0.13.3/lib/gemirro/indexer.rb:86:in `install_indices'
        from /home/lib64/ruby/2.3.0/rubygems/indexer.rb:282:in `generate_index'
        from /home/lib64/ruby/gems/2.3.0/gems/gemirro-0.13.3/lib/gemirro/cli/index.rb:25:in `block (2 levels) in <top (required)>'
        from /home/lib64/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
        from /home/lib64/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
        from /home/lib64/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
        from /home/lib64/ruby/gems/2.3.0/gems/gemirro-0.13.3/bin/gemirro:7:in `<top (required)>'
        from /home/bin64/gemirro:23:in `load'
        from /home/bin64/gemirro:23:in `<main>'
```

**Comment by PierreRambaud** [comment]
Hi and thanks for your feedback,
What's your local rubygem version? (`gem --version`)

**Comment by hemmrich** [comment]
```
bash-4.1$ gem --version
2.5.1
bash-4.1$ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

**Comment by hemmrich** [comment]
The issue seems to be caused by this gem: ```dwradcliffe-test-one-0.0.1.gem```.

**Comment by PierreRambaud** [comment]
Thanks again ;)
