### ISSUE TITLE
Windows - unexpected end of file (Zlib::GzipFile::Error)

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [PierreRambaud/gemirro#46]
@PierreRambaud 

----

The error output:

```
C:\Server\GEMIRRO>gemirro update
C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gemirro-0.13.5/lib/gemirro/versions_file.rb:25:in `read': unexpected end of file (Zlib::GzipFile::Error)
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gemirro-0.13.5/lib/gemirro/versions_file.rb:25:in `load'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gemirro-0.13.5/lib/gemirro/versions_fetcher.rb:24:in `fetch'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gemirro-0.13.5/lib/gemirro/cli/update.rb:15:in `block (2 levels) in <top (required)>'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/gemirro-0.13.5/bin/gemirro:7:in `<top (required)>'
        from C:/Ruby/Ruby23-x64/bin/gemirro:23:in `load'
        from C:/Ruby/Ruby23-x64/bin/gemirro:23:in `<main>'
```

My environment:
```
C:\Server\GEMIRRO>ruby --version
ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]

C:\Server\GEMIRRO>gem --version
2.6.12
```

How can I solve this?

**Comment by SuriyaaKudoIsc** [comment]
Closing this issue because I got no answers.

**Comment by PierreRambaud** [comment]
Very sorry for the delay. too many issues and PR in other projects  :(

In fact, I really don't know how Ruby works under Windows. 
I'm not able to reproduce because I don't have Windows :/

Kind regards
