### ISSUE TITLE
/usr/local/rvm/gems/ruby-2.2.7/gems/gemirro-1.1.0/lib/gemirro/cli/server.rb:73:in `start': uninitialized constant Utils (NameError)

### ISSUE THREAD

**Issue by saxainden** [PierreRambaud/gemirro#57]
Full disclosure: I am just learning Ruby, so I might be missing something obvious.

I have been trying to get gemirro to start on both CentOS 7.5 and Ubuntu 18.04.  Gems update just fine but when I try to run gemirro server --start, I get the following:

[root@localhost mirror]# gemirro server --start
Starting...
/usr/local/rvm/gems/ruby-2.2.7/gems/gemirro-1.1.0/lib/gemirro/cli/server.rb:73:in `start': uninitialized constant Utils (NameError)
	from /usr/local/rvm/gems/ruby-2.2.7/gems/gemirro-1.1.0/lib/gemirro/cli/server.rb:17:in `block (2 levels) in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.7/gems/slop-3.6.0/lib/slop.rb:260:in `call'
	from /usr/local/rvm/gems/ruby-2.2.7/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	from /usr/local/rvm/gems/ruby-2.2.7/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
	from /usr/local/rvm/gems/ruby-2.2.7/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
	from /usr/local/rvm/gems/ruby-2.2.7/gems/gemirro-1.1.0/bin/gemirro:6:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.7/bin/gemirro:23:in `load'
	from /usr/local/rvm/gems/ruby-2.2.7/bin/gemirro:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.2.7/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.2.7/bin/ruby_executable_hooks:15:in `<main>'

Am I missing something? Or what else can I provide to help troubleshoot?

On CentOS, I am using ruby version 2.2.7p470 and on Ubuntu I am using 2.5.1p57.   I decided to test on Ubuntu also in case it was a problem with RHEL/Centos.

Any ideas?
Thanks

**Comment by saxainden** [comment]
Also this is with the default config.rb file. I assume it was working since it downloaded gems just fine.

**Comment by PierreRambaud** [comment]
Hi and thanks for the feedback, I will try to test it as soon as possible (need to download CentOs and having a realy bad connection where I am ^^).

**Comment by saxainden** [comment]
Also happened with same error on Ubunto 18.04.    Thanks!
