### ISSUE TITLE
 Gem::Indexer requires that the XML Builder library be installed: 

### ISSUE THREAD

**Issue by Hassnain-Alvi** [PierreRambaud/gemirro#69]
I have installed gemirro using RVM on my centos 7 system and following steps mentioned in ReadMe but on running 
`gemirro index` it returns following error:
```
/usr/local/rvm/gems/ruby-3.0.0/gems/gemirro-1.3.0/lib/gemirro/indexer.rb:42:in `initialize': Gem::Indexer requires that the XML Builder library be installed: (RuntimeError)
        gem install builder
        from /usr/local/rvm/gems/ruby-3.0.0/gems/gemirro-1.3.0/lib/gemirro/cli/index.rb:22:in `new'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/gemirro-1.3.0/lib/gemirro/cli/index.rb:22:in `block (2 levels) in <top (required)>'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/gemirro-1.3.0/bin/gemirro:7:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-3.0.0/bin/gemirro:23:in `load'
        from /usr/local/rvm/gems/ruby-3.0.0/bin/gemirro:23:in `<main>'
```
I have builder v3.2.4 installed in my system 
Is there any centos 7 packages i need to install to make it work ?

**Comment by PierreRambaud** [comment]
Hi and thanks for your report.
Could you try to add?
```
require 'builder/xchar'
```

**Comment by Hassnain-Alvi** [comment]
> 
> 
> Hi and thanks for your report.
> Could you try to add?
> 
> ```
> require 'builder/xchar'
> ```

should i add it in gemirro cli/index.rb file as mentioned in stack trace?

**Comment by Hassnain-Alvi** [comment]
@PierreRambaud Thanks by adding it in config.rb it worked but now when i start the server i see an error and it failed to start 
Running server with `gemirro server --start `gives following exception 
```
Starting...
done! (PID is 32342)
/usr/local/rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/handler/thin.rb:11:in `run': wrong number of arguments (given 2, expected 1) (ArgumentError)
        from /usr/local/rvm/gems/ruby-3.0.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1526:in `start_server'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1460:in `run!'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/gemirro-1.3.0/lib/gemirro/cli/server.rb:77:in `start'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/gemirro-1.3.0/lib/gemirro/cli/server.rb:19:in `block (2 levels) in <top (required)>'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
        from /usr/local/rvm/gems/ruby-3.0.0/gems/gemirro-1.3.0/bin/gemirro:7:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-3.0.0/bin/gemirro:23:in `load'
        from /usr/local/rvm/gems/ruby-3.0.0/bin/gemirro:23:in `<main>'
```
Is there anything else i need to change?

**Comment by PierreRambaud** [comment]
> @PierreRambaud Thanks by adding it in config.rb it worked but now when i start the server i see an error and it failed to start
> Running server with `gemirro server --start `gives following exception
> 
> ```
> Starting...
> done! (PID is 32342)
> /usr/local/rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/handler/thin.rb:11:in `run': wrong number of arguments (given 2, expected 1) (ArgumentError)
>         from /usr/local/rvm/gems/ruby-3.0.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1526:in `start_server'
>         from /usr/local/rvm/gems/ruby-3.0.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1460:in `run!'
>         from /usr/local/rvm/gems/ruby-3.0.0/gems/gemirro-1.3.0/lib/gemirro/cli/server.rb:77:in `start'
>         from /usr/local/rvm/gems/ruby-3.0.0/gems/gemirro-1.3.0/lib/gemirro/cli/server.rb:19:in `block (2 levels) in <top (required)>'
>         from /usr/local/rvm/gems/ruby-3.0.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
>         from /usr/local/rvm/gems/ruby-3.0.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
>         from /usr/local/rvm/gems/ruby-3.0.0/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
>         from /usr/local/rvm/gems/ruby-3.0.0/gems/gemirro-1.3.0/bin/gemirro:7:in `<top (required)>'
>         from /usr/local/rvm/gems/ruby-3.0.0/bin/gemirro:23:in `load'
>         from /usr/local/rvm/gems/ruby-3.0.0/bin/gemirro:23:in `<main>'
> ```
> 
> Is there anything else i need to change?

I mean in the Gemfile of this project, not in the config.rb file.
As I read, it is something needed for CentOs, but I'm maybe wrong :(

**Comment by Hassnain-Alvi** [comment]
> 
> 
> > @PierreRambaud Thanks by adding it in config.rb it worked but now when i start the server i see an error and it failed to start
> > Running server with `gemirro server --start `gives following exception
> > ```
> > Starting...
> > done! (PID is 32342)
> > /usr/local/rvm/gems/ruby-3.0.0/gems/rack-2.2.3/lib/rack/handler/thin.rb:11:in `run': wrong number of arguments (given 2, expected 1) (ArgumentError)
> >         from /usr/local/rvm/gems/ruby-3.0.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1526:in `start_server'
> >         from /usr/local/rvm/gems/ruby-3.0.0/gems/sinatra-2.0.8.1/lib/sinatra/base.rb:1460:in `run!'
> >         from /usr/local/rvm/gems/ruby-3.0.0/gems/gemirro-1.3.0/lib/gemirro/cli/server.rb:77:in `start'
> >         from /usr/local/rvm/gems/ruby-3.0.0/gems/gemirro-1.3.0/lib/gemirro/cli/server.rb:19:in `block (2 levels) in <top (required)>'
> >         from /usr/local/rvm/gems/ruby-3.0.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
> >         from /usr/local/rvm/gems/ruby-3.0.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
> >         from /usr/local/rvm/gems/ruby-3.0.0/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
> >         from /usr/local/rvm/gems/ruby-3.0.0/gems/gemirro-1.3.0/bin/gemirro:7:in `<top (required)>'
> >         from /usr/local/rvm/gems/ruby-3.0.0/bin/gemirro:23:in `load'
> >         from /usr/local/rvm/gems/ruby-3.0.0/bin/gemirro:23:in `<main>'
> > ```
> > 
> > 
> > Is there anything else i need to change?
> 
> I mean in the Gemfile of this project, not in the config.rb file.
> As I read, it is something needed for CentOs, but I'm maybe wrong :(

This error is printed when i set daemon false. 
Can you tell me what i have to do for CentOS system ?

**Comment by PierreRambaud** [comment]
I didn't manage to reproduce the issue after a fresh install of CentOs 7 using rbenv to get Ruby 3.0.1 :(

**Comment by Hassnain-Alvi** [comment]
> I didn't manage to reproduce the issue after a fresh install of CentOs 7 using rbenv to get Ruby 3.0.1 :( 

Have you tried on CENTOS 7.9?

**Comment by PierreRambaud** [comment]
I'm using `centos-release-7-8.2003.0.el7.centos.x86_64`
Not sure there are a lot of change between both versions
