### ISSUE TITLE
Gemirro index throws ArgumentError

### ISSUE THREAD

**Issue by hemmrich** [PierreRambaud/gemirro#8]
The gem [1234567890_](https://rubygems.org/gems/1234567890_) causes ```gemirro index``` to crash.

```
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1020:in `sort_by': comparison of String with 1234567890 failed (ArgumentError)
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:1020:in `latest_specs'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/indexer.rb:198:in `build_modern_indicies'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/gemirro-0.10.4/lib/gemirro/indexer.rb:148:in `build_indicies'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/indexer.rb:310:in `generate_index'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/gemirro-0.10.4/lib/gemirro/cli/index.rb:22:in `block (2 levels) in <top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:260:in `call'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/gems/2.2.0/gems/gemirro-0.10.4/bin/gemirro:7:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.2/bin/gemirro:23:in `load'
	from /usr/local/rvm/rubies/ruby-2.2.2/bin/gemirro:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.2.2@global/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.2.2@global/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by PierreRambaud** [comment]
Hi and thanks for the feedback.
You can test with the latest commit on master. It's a bug on rubygems library and an error with the original gem: https://github.com/mame/1234567890/blob/v1.1/1234567890.gemspec & https://github.com/mame/1234567890/blob/master/1234567890.gemspec

Tell me if it's ok for you and I will release a new version ;)
Regards

**Comment by hemmrich** [comment]
Hi Pierre, 
Thank you so much for fixing the bug, I'm no longer experiencing that error! However, ```gemirro index``` failed on gem 80legs-0.2.4.gem...is there any way to skip any gems that throw errors and continue to index the rest?

```
E, [2015-07-17T11:33:05.589181 #3397] ERROR -- : Unable to process /Users/hemmrich/Desktop/tmp/gemirro_mirror/public/gems/80legs-0.2.4.gem
package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /Users/hemmrich/Desktop/tmp/gemirro_mirror/public/gems/80legs-0.2.4.gem (Gem::Package::FormatError)
```

**Comment by PierreRambaud** [comment]
Hi again,

I can't reproduce this error, seems to be a download problem.
```
got@GoT-M17xR3:~$ cd projects/ruby/gemirro/
got@GoT-M17xR3:~/projects/ruby/gemirro$ bundle exec bin/gemirro init /tmp/test
Initialized empty mirror in /tmp/test
got@GoT-M17xR3:~/projects/ruby/gemirro$ bundle exec bin/gemirro update -c /tmp/test/config.rb 
I, [2015-07-18T10:39:40.880910 #2273]  INFO -- : Updating rubygems (http://rubygems.org)
I, [2015-07-18T10:39:45.658218 #2273]  INFO -- : Fetching 80legs-0.1.0.gem
I, [2015-07-18T10:39:48.403401 #2273]  INFO -- : Fetching 80legs-0.2.0.gem
I, [2015-07-18T10:39:53.748439 #2273]  INFO -- : Fetching 80legs-0.2.1.gem
I, [2015-07-18T10:39:57.893543 #2273]  INFO -- : Fetching 80legs-0.2.2.gem
I, [2015-07-18T10:40:04.074133 #2273]  INFO -- : Fetching 80legs-0.2.3.gem
I, [2015-07-18T10:40:08.050978 #2273]  INFO -- : Fetching 80legs-0.2.4.gem
I, [2015-07-18T10:40:11.541222 #2273]  INFO -- : Fetching 80legs-0.2.5.gem
got@GoT-M17xR3:~/projects/ruby/gemirro$ bundle exec bin/gemirro index -c /tmp/test/config.rb 
I, [2015-07-18T10:40:37.961625 #14282]  INFO -- : Generating indexes
got@GoT-M17xR3:~/projects/ruby/gemirro$
```
Regards

**Comment by hemmrich** [comment]
You're right, redownloading fixed the issue. However, it would still be great if there was an option to skip any errors while indexing, since I keep running into issues while running the ```gemirro index``` command:


```
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/version.rb:163:in `dup': can't dup Float (TypeError)
        from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/version.rb:163:in `version'
        from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:2034:in `original_name'
        from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/indexer.rb:139:in `block (2 levels) in build_marshal_gemspecs'
        from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:895:in `block in each'
        from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:894:in `each'
        from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:894:in `each'
        from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/indexer.rb:137:in `block in build_marshal_gemspecs'
        from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems.rb:907:in `time'
        from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/indexer.rb:136:in `build_marshal_gemspecs'
        from /usr/local/rvm/gems/ruby-2.2.2@global/gems/gemirro-0.10.4/lib/gemirro/indexer.rb:147:in `build_indicies'
        from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/indexer.rb:310:in `generate_index'
        from /usr/local/rvm/gems/ruby-2.2.2@global/gems/gemirro-0.10.4/lib/gemirro/cli/index.rb:22:in `block (2 levels) in <top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.2@global/gems/slop-3.6.0/lib/slop.rb:260:in `call'
        from /usr/local/rvm/gems/ruby-2.2.2@global/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
        from /usr/local/rvm/gems/ruby-2.2.2@global/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
        from /usr/local/rvm/gems/ruby-2.2.2@global/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
        from /usr/local/rvm/gems/ruby-2.2.2@global/gems/gemirro-0.10.4/bin/gemirro:7:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.2.2/bin/gemirro:23:in `load'
        from /usr/local/rvm/rubies/ruby-2.2.2/bin/gemirro:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.2.2@global/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.2.2@global/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by PierreRambaud** [comment]
Which version of rubygems are you using?
```
$ gem --version
2.4.8 # Mine
```

**Comment by hemmrich** [comment]
I'm also using version 2.4.8.

**Comment by PierreRambaud** [comment]
Can you show me which gem are you adding so I could reproduce this bug :)

**Comment by hemmrich** [comment]
All 600,000+ versions of all gems hosted on rubygems.org...I'll try to narrow down which gem(s) caused the error :)

**Comment by hemmrich** [comment]
It seems to be failing on: ```#<Gem::Specification name=acts-as-linkable version=0.0.1.5>```

```
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/indexer.rb:198:in `build_modern_indicies': undefined method `reject' for nil:NilClass (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.2.2@global/gems/gemirro-0.10.4/lib/gemirro/indexer.rb:148:in `build_indicies'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/indexer.rb:310:in `generate_index'
	from /usr/local/rvm/gems/ruby-2.2.2@global/gems/gemirro-0.10.4/lib/gemirro/cli/index.rb:22:in `block (2 levels) in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.2@global/gems/slop-3.6.0/lib/slop.rb:260:in `call'
	from /usr/local/rvm/gems/ruby-2.2.2@global/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	from /usr/local/rvm/gems/ruby-2.2.2@global/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
	from /usr/local/rvm/gems/ruby-2.2.2@global/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
	from /usr/local/rvm/gems/ruby-2.2.2@global/gems/gemirro-0.10.4/bin/gemirro:7:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.2/bin/gemirro:23:in `load'
	from /usr/local/rvm/rubies/ruby-2.2.2/bin/gemirro:23:in `<main>'
```

**Comment by hemmrich** [comment]
If you want to reproduce the bug, try mirroring all gems that start with a number or an a using [rubygems-mirror](https://github.com/rubygems/rubygems-mirror) and then trying to call ```gemirro index```.

**Comment by hemmrich** [comment]
There are a few other gems that throw errors in the newest version (0.10.5) of gemirro:

```
ERROR -- : Unable to process /home/hemmrich/gemirro/public/gems/AbsoluteRenamer-system-0.1.0.gem
package content (data.tar.gz) is missing in /home/hemmrich/gemirro/public/gems/AbsoluteRenamer-system-0.1.0.gem (Gem::Package::FormatError)
	/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:587:in `verify_files'
	/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:508:in `block (2 levels) in verify'
	/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/package/tar_reader.rb:28:in `new'
	/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:505:in `block in verify'
	/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/open-uri.rb:36:in `open'
	/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/open-uri.rb:36:in `open'
	/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/package/file_source.rb:29:in `with_read_io'
	/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:504:in `verify'
	/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:485:in `spec'
	/usr/local/rvm/gems/ruby-2.2.2/gems/gemirro-0.10.5/lib/gemirro/indexer.rb:179:in `block in map_gems_to_specs'
	/usr/local/rvm/gems/ruby-2.2.2/gems/gemirro-0.10.5/lib/gemirro/indexer.rb:171:in `map'
	/usr/local/rvm/gems/ruby-2.2.2/gems/gemirro-0.10.5/lib/gemirro/indexer.rb:171:in `map_gems_to_specs'
	/usr/local/rvm/gems/ruby-2.2.2/gems/gemirro-0.10.5/lib/gemirro/indexer.rb:156:in `build_indicies'
	/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/indexer.rb:310:in `generate_index'
	/usr/local/rvm/gems/ruby-2.2.2/gems/gemirro-0.10.5/lib/gemirro/cli/index.rb:22:in `block (2 levels) in <top (required)>'
	/usr/local/rvm/gems/ruby-2.2.2@global/gems/slop-3.6.0/lib/slop.rb:260:in `call'
	/usr/local/rvm/gems/ruby-2.2.2@global/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	/usr/local/rvm/gems/ruby-2.2.2@global/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
	/usr/local/rvm/gems/ruby-2.2.2@global/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
	/usr/local/rvm/gems/ruby-2.2.2/gems/gemirro-0.10.5/bin/gemirro:7:in `<top (required)>'
	/usr/local/rvm/gems/ruby-2.2.2/bin/gemirro:23:in `load'
	/usr/local/rvm/gems/ruby-2.2.2/bin/gemirro:23:in `<main>'
	/usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	/usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
/usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/indexer.rb:129:in `block in build_marshal_gemspecs': undefined method `default_gem?' for true:TrueClass (NoMethodError)
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:895:in `block in each'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:894:in `each'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/specification.rb:894:in `each'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/indexer.rb:129:in `count'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/indexer.rb:129:in `build_marshal_gemspecs'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/gemirro-0.10.5/lib/gemirro/indexer.rb:158:in `build_indicies'
	from /usr/local/rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/indexer.rb:310:in `generate_index'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/gemirro-0.10.5/lib/gemirro/cli/index.rb:22:in `block (2 levels) in <top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.2@global/gems/slop-3.6.0/lib/slop.rb:260:in `call'
	from /usr/local/rvm/gems/ruby-2.2.2@global/gems/slop-3.6.0/lib/slop.rb:260:in `parse!'
	from /usr/local/rvm/gems/ruby-2.2.2@global/gems/slop-3.6.0/lib/slop.rb:235:in `parse!'
	from /usr/local/rvm/gems/ruby-2.2.2@global/gems/slop-3.6.0/lib/slop.rb:211:in `parse'
	from /usr/local/rvm/gems/ruby-2.2.2/gems/gemirro-0.10.5/bin/gemirro:7:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.2/bin/gemirro:23:in `load'
	from /usr/local/rvm/gems/ruby-2.2.2/bin/gemirro:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

Some other gems that cause errors:
```
active_directory-1.5.3.gem
active_directory-1.5.4.gem
appraiser-0.1.2.gem
appraiser-0.1.3.gem
appraiser-0.1.4.gem
appraiser-0.1.5.gem
archive-tar-minitar-0.5.1.gem
autotestforphp-0.0.3.gem
```

**Comment by PierreRambaud** [comment]
Thanks a lot, I will have a look today :)

**Comment by PierreRambaud** [comment]
Is it better now? Some gems seem broken --'

**Comment by hemmrich** [comment]
It seems to be a lot better now (at least for the 120,000 gems I've been testing it with), but there are some gems being skipped now that never caused any issues before:

```
W, [2015-07-21T11:07:31.202000 #5490]  WARN -- : Skipping misnamed gem: /Users/hemmrich/gemirro/public/gems/1234567890_-1.0.gem should be named 1234567890-1.0
W, [2015-07-21T11:08:06.171685 #5490]  WARN -- : Skipping misnamed gem: /Users/hemmrich/gemirro/public/gems/actionpool-0.2.2.gem should be named ActionPool-0.2.2
W, [2015-07-21T11:08:06.173717 #5490]  WARN -- : Skipping misnamed gem: /Users/hemmrich/gemirro/public/gems/actionpool-0.2.3.gem should be named ActionPool-0.2.3
W, [2015-07-21T11:08:06.269937 #5490]  WARN -- : Skipping misnamed gem: /Users/hemmrich/gemirro/public/gems/actiontimer-0.1.1.gem should be named ActionTimer-0.1.1
W, [2015-07-21T11:08:06.271813 #5490]  WARN -- : Skipping misnamed gem: /Users/hemmrich/gemirro/public/gems/actiontimer-0.2.1.gem should be named ActionTimer-0.2.1
W, [2015-07-21T11:08:47.007410 #5490]  WARN -- : Skipping misnamed gem: /Users/hemmrich/gemirro/public/gems/activesambaldap-0.0.7.gem should be named ActiveSambaLdap-0.0.7
W, [2015-07-21T11:13:39.879228 #5490]  WARN -- : Skipping misnamed gem: /Users/hemmrich/gemirro/public/gems/AutoNZB-0.5.4.gem should be named autonzb-0.5.4
W, [2015-07-21T11:14:13.180164 #5490]  WARN -- : Skipping misnamed gem: /Users/hemmrich/gemirro/public/gems/babelfish-0.0.1.gem should be named Babelfish-0.0.1
W, [2015-07-21T11:14:36.772043 #5490]  WARN -- : Skipping misnamed gem: /Users/hemmrich/gemirro/public/gems/banana-0.0.1.gem should be named Banana-0.0.1
W, [2015-07-21T11:15:51.428207 #5490]  WARN -- : Skipping misnamed gem: /Users/hemmrich/gemirro/public/gems/bigcat-1.0.2.gem should be named BigCat-1.0.2
W, [2015-07-21T11:26:44.209798 #5490]  WARN -- : Skipping misnamed gem: /Users/hemmrich/gemirro/public/gems/collegiatelink-0.0.3.gem should be named CollegiateLink-0.0.3
```

Is it possible to ignore the case when comparing the names?

Also, the newer versions give me this warning:
```
WARN: Unresolved specs during Gem::Specification.reset:
      rack (~> 1.0, ~> 1.4)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
```
It doesn't seem to be causing problems but I thought I'd let you know anyways :)

**Comment by hemmrich** [comment]
Also, is it possible to add additional logging during the indexing phase (possibly like in https://github.com/PierreRambaud/gemirro/pull/9)? It's nice to be able to see the progress when indexing close to 600,000 gems ;)

**Comment by PierreRambaud** [comment]
Of course! (thanks again for the PR)

**Comment by hemmrich** [comment]
Indexing of all the gems was successful!! However, I'm now getting this internal server error when trying to hit any server endpoint:
```
Unexpected error while processing request: undefined method `downcase' for nil:NilClass
        /usr/local/rvm/gems/ruby-2.2.2@global/gems/gemirro-0.10.5/lib/gemirro/gem_version_collection.rb:76:in `block in by_name'
        /usr/local/rvm/gems/ruby-2.2.2@global/gems/gemirro-0.10.5/lib/gemirro/gem_version_collection.rb:75:in `each'
        /usr/local/rvm/gems/ruby-2.2.2@global/gems/gemirro-0.10.5/lib/gemirro/gem_version_collection.rb:75:in `sort_by'
        /usr/local/rvm/gems/ruby-2.2.2@global/gems/gemirro-0.10.5/lib/gemirro/gem_version_collection.rb:75:in `sort_by!'
        /usr/local/rvm/gems/ruby-2.2.2@global/gems/gemirro-0.10.5/lib/gemirro/gem_version_collection.rb:75:in `by_name'
        /usr/local/rvm/gems/ruby-2.2.2@global/gems/gemirro-0.10.5/lib/gemirro/gem_version_collection.rb:94:in `find_by_name'
        /usr/local/rvm/gems/ruby-2.2.2@global/gems/gemirro-0.10.5/lib/gemirro/server.rb:69:in `block in <class:Server>'
        /usr/local/rvm/gems/ruby-2.2.2@global/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
        /usr/local/rvm/gems/ruby-2.2.2@global/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
```

**Comment by hemmrich** [comment]
There's some gem that causes 

```
@grouped.sort_by! do |name, _collection|
  name.downcase
end
```

in [gem_version_collection.rb] (https://github.com/PierreRambaud/gemirro/blob/master/lib/gemirro/gem_version_collection.rb) on line 76 to fail. Commenting out the 3 lines above fixes the issue I'm having right now. Is there any reason why trying to hit a specific gem endpoint (example: <server_url>:9999/gem/rake) causes the by_name function to get called? It seems unnecessary to sort all of the gems every time a request is made for a particular gem.

**Comment by PierreRambaud** [comment]
Is it better with the latest commit?
Also, I'm right with you, sorting all the gems every time a request is made isn't a good idea, I will try something as soon as possible. Otherwise if you have any idea about how to improve this functionality, don't hesitate to tell me how :)

Thanks again for your feeback :)

**Comment by hemmrich** [comment]
Yup, the latest commit seems to have fixed the error! Is there any way you could push a new version of this gem to rubygems.org?
As far as the sorting is concerned, I'll have to keep looking into the server functionality as I have no ideas at this point.

No problem, thank you so much for your quick responses!

**Comment by PierreRambaud** [comment]
I just add a new parameter in config.rb `update_on_fetch`, you can set it to false to not re-index all the gems when fetching new gem.
More, I think only the new downloaded gem must be re-index.

**Comment by PierreRambaud** [comment]
Should be fix with latests commits.
